t_Registros = {'A':'111','B':'000','C':'001','D':'010','H':'100','L':'101',
              'BC':'00','DE':'01','HL':'10','SP':'11','IX':'10','IY':'10'}

registros = ['A', 'B', 'C', 'D', 'H', 'L', 'BC', 'DE', 'HL', 'SP', 'IX', 'IY']


t_nemonicos={
    "NOP": [1, '00'],
    "INC B": [1, '04'],
    "DEC B": [1, '05'],
    "LD B, N": [2, '06xx'],
    "EX AF, AF'": [1, '08'],
    "LD A, (BC)": [1, '0A'],
    "DEC BC": [1, '0B'],
    "INC C": [1, '0C'],
    "DEC C": [1, '0D'],
    "LD C, N": [2, '0Exx'],
    "RRCA": [1, '0F'],
    "DJNZ DIS": [2, '10xx'],
    "LD DE, NN": [3, '11xxxx'],
    "LD (DE), A": [1, '12'],
    "INC DE": [1, '13'],
    "INC D": [1, '14'],
    "DEC D": [1, '15'],
    "LD D, N": [2, '16xx'],
    "RLA": [1, '17'],
    "JR Z, DIS": [2, '18xx'],
    "ADD HL, DE": [1, '19'],
    "LD A, (DE)": [1, '1A'],
    "DEC DE": [1, '1B'],
    "INC E": [1, '1C'],
    "DEC E": [1, '1D'],
    "LD E, N": [2, '1Exx'],
    "RRA": [1, '1F'],
    "JR NZ, DIS": [2, '20xx'],
    "LD HL, NN": [3, '21xxxx'],
    "LD (NN), HL": [3, '22xxxx'],
    "INC HL": [1, '23'],
    "INC H": [1, '24'],
    "DEC H": [1, '25'],
    "LD H, N": [2, '26xx'],
    "DAA": [1, '27'],
    "JR Z, DIS": [2, '28xx'],
    "ADD HL, HL": [1, '29'],
    "LD (HL), (NN)": [3, '2Axxxx'],
    "DEC HL": [1, '2B'],
    "INC L": [1, '2C'],
    "DEC L": [1, '2D'],
    "LD L, N": [2, '2Exx'],
    "CPL": [1, '2F'],
    "JR NC, DIS": [2, '30xx'],
    "LD SP, NN": [3, '31xxxx'],
    "LD (NN), A": [3, '32xxxx'],
    "INC SP": [1, '33'],
    "INC (HL)": [1, '34'],
    "DEC (HL)": [1, '35'],
    "LD (HL), N": [2, '36xx'],
    "SCF": [1, '37'],
    "JR C, DIS": [2, '38xx'],
    "ADD HL, SP": [1, '39'],
    "LD A, (NN)": [3, '3Axxxx'],
    "DEC SP": [1, '3B'],
    "INC A": [1, '3C'],
    "DEC A": [1, '3D'],
    "CCF": [1, '3F'],
    "LD B, B": [1, '40'],
    "LD B, C": [1, '41'],
    "LD B, D": [1, '42'],
    "LD B, E": [1, '43'],
    "LD B, H, NN": [1, '44'],
    "LD B, L": [1, '45'],
    "LD B, (HL)": [1, '46'],
    "LD B, A": [1, '47'],
    "LD C, B": [1, '48'],
    "LD C, C": [1, '49'],
    "LD C, D": [1, '4A'],
    "LD C, E": [1, '4B'],
    "LD C, H": [1, '4C'],
    "LD C, L": [1, '4D'],
    "LD C, (HL)": [1, '4E'],
    "LD C, A": [1, '4F'],
    "LD D, B": [1, '50'],
    "LD D, C": [1, '51'],
    "LD D, D": [1, '52'],
    "LD D, E": [1, '53'],
    "LD D, H": [1, '54'],
    "LD D, L": [1, '55'],
    "LD D, (HL)": [1, '56'],
    "LD D, A": [1, '57'],
    "LD E, B": [1, '58'],
    "LD E, C": [1, '59'],
    "LD E, D": [1, '5A'],
    "LD E, E": [1, '5B'],
    "LD E, H": [1, '5C'],
    "LD E, L": [1, '5D'],
    "LD E, (HL)": [1, '5E'],
    "LD E, A": [1, '5F'],
    "LD H, B": [1, '60'],
    "LD H, C": [1, '61'],
    "LD H, D": [1, '62'],
     "ADC A, (HL)": [2, '8E'],
    "ADC A, (IX + d)": [3, 'DD8Exx'],
    "ADC A, (IY + d)": [3, 'FD8Exx'],
    "ADC A, A": [1, '8F'],
    "ADC A, B": [1, '88'],
    "ADC A, C": [1, '89'],
    "ADC A, D": [1, '8A'],
    "ADC A, E": [1, '8B'],
    "ADC A, H": [1, '8C'],
    "ADC A, L": [1, '8D'],
    "ADC A, N": [2, 'CExx'],
    "ADC HL, BC": [2, 'ED4A'],
    "ADC HL, DE": [2, 'ED5A'],
    "ADC HL, HL": [2, 'ED6A'],
    "ADC HL, SP": [2, 'ED7A'],
    "ADD A, (HL)": [1, '86'],
    "ADD A, (IX + d)": [3, 'DD86xx'],
    "ADD A, (IY + d)": [3, 'FD86xx'],
    "ADD A, A": [1, '87'],
    "ADD A, B": [1, '80'],
    "ADD A, C": [1, '81'],
    "ADD A, D": [1, '82'],
    "ADD A, E": [1, '83'],
    "ADD A, H": [1, '84'],
    "ADD A, L": [1, '85'],
    "ADD A, N": [2, 'C6xx'],
    "ADD HL, BC": [1, '09'],
    "ADD HL, DE": [1, '19'],
    "ADD HL, HL": [1, '29'],
    "ADD HL, SP": [1, '39'],
    "ADD IX, BC": [2, 'DD09'],
    "ADD IX, DE": [2, 'DD19'],
    "ADD IX, IX": [2, 'DD29'],
    "ADD IX, SP": [2, 'DD39'],
    "ADD IY, BC": [2, 'FD09'],
    "ADD IY, DE": [2, 'FD19'],
    "ADD IY, IY": [2, 'FD29'],
    "ADD IY, SP": [2, 'FD39'],
    "AND (HL)": [1, 'A6'],
    "AND (IX + d)": [3, 'DDA6xx'],
    "AND (IY + d)": [3, 'FDA6xx'],
    "AND A": [1, 'A7'],
    "AND B": [1, 'A0'],
    "AND C": [1, 'A1'],
    "AND D": [1, 'A2'],
    "AND E": [1, 'A3'],
    "AND H": [1, 'A4'],
    "AND L": [1, 'A5'],
    "AND N": [2, 'E6xx'],
    "BIT 0, B": [2, 'CB40'],
    "BIT 0, C": [2, 'CB41'],
    "BIT 0, D": [2, 'CB42'],
    "BIT 0, E": [2, 'CB43'],
    "BIT 0, H": [2, 'CB44'],
    "BIT 0, L": [2, 'CB45'],
    "BIT 0, (HL)": [2, 'CB46'],
    "BIT 0, A": [2, 'CB47'],
    "BIT 0, (IX + d)": [4, 'DDCBxx46'],
    "BIT 0, (IY + d)": [4, 'FDCBxx46'],
    "BIT 1, B": [2, 'BC48'],
    "BIT 1, C": [2, 'CB49'],
    "BIT 1, D": [2, 'CB4A'],
    "BIT 1, E": [2, 'CB4B'],
    "BIT 1, H": [2, 'CB4C'],
    "BIT 1, L": [2, 'CB4D'],
    "BIT 1, (HL)": [2, 'CB4E'],
    "BIT 1, A": [2, 'CB4F'],
    "BIT 1, (IX + d)": [4, 'DDCBxx4E'],
    "BIT 1, (IY + d)": [4, 'FDCBxx4E'],
    "BIT 2, B": [2, 'CB50'],
    "BIT 2, C": [2, 'CB51'],
    "BIT 2, D": [2, 'CB52'],
    "BIT 2, E": [2, 'CB53'],
    "BIT 2, H": [2, 'CB54'],
    "BIT 2, L": [2, 'CB55'],
    "BIT 2, (HL)": [2, 'CB56'],
    "BIT 2, A": [2, 'CB57'],
    "BIT 2, (IX + d)": [4, 'DDCBxx56'],
    "BIT 2, (IY + d)": [4, 'FDCBxx56'],
    "BIT 3, B": [2, 'CB58'],
    "BIT 3, C": [2, 'CB59'],
    "BIT 3, D": [2, 'CB5A'],
    "BIT 3, E": [2, 'CB5B'],
    "BIT 3, H": [2, 'CB5C'],
    "BIT 3, L": [2, 'CB5D'],
    "BIT 3, (HL)": [2, 'CB5E'],
    "BIT 3, A": [2, 'CB5F'],
    "BIT 3, (IX + d)": [4, 'DDCBxx5E'],
    "BIT 3, (IY + d)": [4, 'FDCBxx5E'],
    "BIT 4, B": [2, 'CB60'],
    "BIT 4, C": [2, 'CB61'],
    "BIT 4, D": [2, 'CB62'],
    "BIT 4, E": [2, 'CB63'],
    "BIT 4, H": [2, 'CB64'],
    "BIT 4, L": [2, 'CB65'],
    "BIT 4, (HL)": [2, 'CB66'],
    "BIT 4, A": [2, 'CB67'],
    "BIT 4, (IX + d)": [4, 'DDCBxx66'],
    "BIT 4, (IY + d)": [4, 'FDCBxx66'],
     "BIT 5, A": [2, 'CB6F'],
    "BIT 5, B": [2, 'CB68'],
    "BIT 5, C": [2, 'CB69'],
    "BIT 5, D": [2, 'CB6A'],
    "BIT 5, E": [2, 'CB6B'],
    "BIT 5, H": [2, 'CB6C'],
    "BIT 5, L": [2, 'CB6D'],
    "BIT 5, (HL)": [2, 'CB6E'],
    "BIT 5, (IX + d)": [4, 'DDCBxx6E'],
    "BIT 5, (IY + d)": [4, 'FDCBxx6E'],
    "BIT 6, A": [2, 'CB77'],
    "BIT 6, B": [2, 'CB70'],
    "BIT 6, C": [2, 'CB71'],
    "BIT 6, D": [2, 'CB72'],
    "BIT 6, E": [2, 'CB73'],
    "BIT 6, H": [2, 'CB74'],
    "BIT 6, L": [2, 'CB75'],
    "BIT 6, (HL)": [2, 'CB76'],
    "BIT 6, (IX + d)": [4, 'DDCBxx76'],
    "BIT 6, (IY + d)": [4, 'FDCBxx76'],
    "BIT 7, A": [2, 'CB7F'],
    "BIT 7, B": [2, 'CB78'],
    "BIT 7, C": [2, 'CB79'],
    "BIT 7, D": [2, 'CB7A'],
    "BIT 7, E": [2, 'CB7B'],
    "BIT 7, H": [2, 'CB7C'],
    "BIT 7, L": [2, 'CB7D'],
    "BIT 7, (HL)": [2, 'CB7E'],
    "BIT 7, (IX + d)": [4, 'DDCBxx7E'],
    "BIT 7, (IY + d)": [4, 'FDCBxx7E'],
    "CALL C, NN": [3, 'DCxxxx'],
    "CALL M, NN": [3, 'FCxxxx'],
    "CALL NC, NN": [3, 'D4xxxx'],
    "CALL NN": [3, 'CDxxxx'],
    "CALL NZ, NN": [3, 'C4xxxx'],
    "CALL P, NN": [3, 'F4xxxx'],
    "CALL PE, NN": [3, 'ECxxxx'],
    "CALL PO, NN": [3, 'E4xxxx'],
    "CALL Z, NN": [3, 'CCxxxx'],
    "CCF": [1, '3F'],
    "CP (HL)": [1, 'BE'],
    "CP (IX + d)": [3, 'DDBExx'],
    "CP (IY + d)": [3, 'FDBExx'],
    "CP A": [1, 'BF'],
    "CP B": [1, 'B8'],
    "CP C": [1, 'B9'],
    "CP D": [1, 'BA'],
    "CP E": [1, 'BB'],
    "CP H": [1, 'BC'],
    "CP L": [1, 'BD'],
    "CP N": [2, 'FExx'],
    "CPD": [1, 'EDA9'],
    "CPDR": [1, 'EDB9'],
    "CPI": [1, 'EDA1'],
    "CPIR": [1, 'EDB1'],
    "CPL": [1, '2F'],
    "DAA": [1, '27'],
    "DEC (HL)": [1, '35'],
    "DEC (IX + d)": [3, 'DD35xx'],
    "DEC (IY + d)": [3, 'FD35xx'],
    "DEC A": [1, '3D'],
    "DEC B": [1, '05'],
    "DEC BC": [1, '0B'],
    "DEC C": [1, '0D'],
    "DEC D": [1, '15'],
    "DEC DE": [1, '1B'],
    "DEC E": [1, '1D'],
    "DEC H": [1, '25'],
    "DEC HL": [1, '2B'],
    "DEC IX": [2, 'DD2B'],
    "DEC IY": [2, 'FD2B'],
    "DEC L": [1, '2D'],
    "DEC SP": [1, '3B'],
    "DI": [1, 'F3'],
    "DJNZ DIS": [2, '10xx'],
    "EI": [1, 'FB'],
    "EX (SP), HL": [1, 'E3'],
    "EX (SP), IX": [2, 'DDE3'],
    "EX (SP), IY": [2, 'FDE3'],
    "EX AF, AF'": [1, '08'],
    "EX DE, HL": [1, 'EB'],
    "EXX": [1, 'D9'],
    "HALT": [1, '76'],
    "IM 0": [1, 'ED46'],
    "IM 1": [1, 'ED56'],
    "IM 2": [1, 'ED5E'],
    "IN A, (C)": [2, 'ED78'],
    "IN A, (N)": [2, 'DBxx'],
    "IN B, (C)": [2, 'ED40'],
    "IN C, (C)": [2, 'ED48'],
    "IN D, (C)": [2, 'ED50'],
    "IN E, (C)": [2, 'ED58'],
    "IN H, (C)": [2, 'ED60'],
    "IN L, (C)": [2, 'ED68'],
    "INC (HL)": [1, '34'],
    "INC (IX + d)": [3, 'DD34xx'],
    "INC (IY + d)": [3, 'FD34xx'],
    "INC A": [1, '3C'],
    "INC B": [1, '04'],
    "INC BC": [1, '03'],
    "INC C": [1, '0C'],
    "INC D": [1, '14'],
    "INC DE": [1, '13'],
    "INC E": [1, '1C'],
    "INC H": [1, '24'],
    "INC HL": [1, '23'],
    "INC IX": [2, 'DD23'],
    "INC IY": [2, 'FD23'],
    "INC L": [1, '2C'],
    "INC SP": [1, '33'],
    "IND": [1, 'EDAA'],
    "INDR": [1, 'EDBA'],
    "INI": [1, 'EDA2'],
    "INIR": [1, 'EDB2'],
    "JP (HL)": [1, 'E9'],
    "JP (IX)": [2, 'DDE9'],
    "JP (IY)": [2, 'FDE9'],
    "JP C, NN": [3, 'DAxxxx'],
    "JP M, NN": [3, 'FAxxxx'],
    "JP NC, NN": [3, 'D2xxxx'],
    "JP NN": [3, 'C3xxxx'],
    "JP NZ, NN": [3, 'C2xxxx'],
    "JP P, NN": [3, 'F2xxxx'],
    "JP PE, NN": [3, 'EAxxxx'],
    "JP PO, NN": [3, 'E2xxxx'],
    "JP Z, NN": [3, 'CAxxxx'],
    "JR C, DIS": [2, '38xx'],
    "JR DIS": [2, '18xx'],
    "JR NC, DIS": [2, '30xx'],
    "JR NZ, DIS": [2, '20xx'],
    "JR Z, DIS": [2, '28xx'],
    "JR DIS": [2, '18xx'],
    "LD (BC), A": [1, '02'],
    "LD (DE), A": [1, '12'],
    "LD (HL), A": [1, '77'],
    "LD (HL), B": [1, '70'],
    "LD (HL), C": [1, '71'],
    "LD (HL), D": [1, '72'],
    "LD (HL), E": [1, '73'],
    "LD (HL), H": [1, '74'],
    "LD (HL), L": [1, '75'],
    "LD (IX + d), A": [3, 'DD77xx'],
    "LD (IY + d), A": [3, 'FD77xx'],
    "LD (NN), BC": [4, 'ED43xxxx'],
    "LD (NN), DE": [4, 'ED53xxxx'],
    "LD (NN), HL": [3, '22xxxx'],
    "LD (NN), IX": [4, 'DD22xxxx'],
    "LD (NN), IY": [4, 'FD22xxxx'],
    "LD (NN), SP": [4, 'ED73xxxx'],
    "LD A, (BC)": [1, '0A'],
    "LD A, (DE)": [1, '1A'],
    "LD A, (HL)": [1, '7E'],
    "LD A, (IX + d)": [3, 'DD7Exx'],
    "LD A, (IY + d)": [3, 'FD7Exx'],
    "LD A, A": [1, '7F'],
    "LD A, B": [1, '78'],
    "LD A, C": [1, '79'],
    "LD A, D": [1, '7A'],
    "LD A, E": [1, '7B'],
    "LD A, H": [1, '7C'],
    "LD A, I": [2, 'ED57'],
    "LD A, L": [1, '7D'],
    "LD A, N": [2, '3Exx'],
    "LD A, (NN)": [3, '3Axxxx'],
    "LD B, (HL)": [1, '46'],
    "LD B, (IX + d)": [3, 'DD46xx'],
    "LD B, (IY + d)": [3, 'FD46xx'],
    "LD B, A": [1, '47'],
    "LD B, B": [1, '40'],
    "LD B, C": [1, '41'],
    "LD B, D": [1, '42'],
    "LD B, E": [1, '43'],
    "LD B, H, NN": [1, '44'],
    "LD B, L": [1, '45'],
    "LD B, N": [2, '06xx'],
    "LD BC, (NN)": [3, 'ED4Bxxxx'],
    "LD BC, NN": [3, '01xxxx'],
    "LD C, (IX + d)": [3, 'DD4Exx'],
    "LD C, (IY + d)": [3, 'FD4Exx'],
    "LD C, (HL)": [1, '4E'],
    "LD C, A": [1, '4F'],
    "LD C, B": [1, '48'],
    "LD C, C": [1, '49'],
    "LD C, D": [1, '4A'],
    "LD C, E": [1, '4B'],
    "LD C, H": [1, '4C'],
    "LD C, L": [1, '4D'],
    "LD C, N": [2, '0Exx'],
    "LD D, (HL)": [1, '56'],
    "LD D, (IX + d)": [3, 'DD56xx'],
    "LD D, (IY + d)": [3, 'FD56xx'],
    "LD D, A": [1, '57'],
    "LD D, B": [1, '50'],
    "LD D, C": [1, '51'],
    "LD D, D": [1, '52'],
    "LD D, E": [1, '53'],
    "LD D, H": [1, '54'],
    "LD D, L": [1, '55'],
    "LD D, N": [2, '16xx'],
    "LD E, (HL)": [1, '5E'],
    "LD E, (IX + d)": [3, 'DD5Exx'],
    "LD E, (IY + d)": [3, 'FD5Exx'],
    "LD E, A": [1, '5F'],
    "LD E, B": [1, '58'],
    "LD E, C": [1, '59'],
    "LD E, D": [1, '5A'],
    "LD E, E": [1, '5B'],
    "LD E, H": [1, '5C'],
    "LD E, L": [1, '5D'],
    "LD E, N": [2, '1Exx'],
    "LD H, (HL)": [1, '66'],
    "LD H, (IX + d)": [3, 'DD66xx'],
    "LD H, (IY + d)": [3, 'FD66xx'],
    "LD H, A": [1, '67'],
    "LD H, B": [1, '60'],
    "LD H, C": [1, '61'],
    "LD H, D": [1, '62'],
    "LD H, E": [1, '63'],
    "LD H, H": [1, '64'],
    "LD H, L": [1, '65'],
    "LD H, N": [2, '26xx'],
    "LD HL, (NN)": [3, '2Axxxx'],
    "LD HL, NN": [3, '21xxxx'],
    "LD IY, (NN)": [3, 'FD2Axxxx'],
    "LD IY, NN": [3, 'FD21xxxx'],
    "LD IX, (NN)": [3, 'DD2Axxxx'],
    "LD IX, NN": [3, 'DD21xxxx'],
    "LD L, (HL)": [1, '6E'],
    "LD L, (IX + d)": [3, 'DD6Exx'],
    "LD L, (IY + d)": [3, 'FD6Exx'],
    "LD L, A": [1, '6F'],
    "LD L, B": [1, '68'],
    "LD L, C": [1, '69'],
    "LD L, D": [1, '6A'],
    "LD L, E": [1, '6B'],
    "LD L, H": [1, '6C'],
    "LD L, L": [1, '6D'],
    "LD L, N": [2, '2Exx'],
     "LD SP, (NN)": [3, 'ED7Bxxxx'],
    "LD SP, HL": [1, 'F9'],
    "LD SP, IX": [2, 'DDF9'],
    "LD SP, IY": [2, 'FDF9'],
     "LDD": [1, 'EDA8'],
    "LDDR": [1, 'EDB8'],
    "LDI": [1, 'EDA0'],
    "LDIR": [1, 'EDB0'],
    "NEG": [1, 'ED44'],
    "NOP": [1, '00'],
    "OR (HL)": [1, 'B6'],
    "OR (IX + d)": [3, 'DDB6xx'],
    "OR (IY + d)": [3, 'FDB6xx'],
    "OR A": [1, 'B7'],
    "OR B": [1, 'B0'],
    "OR C": [1, 'B1'],
    "OR D": [1, 'B2'],
    "OR E": [1, 'B3'],
    "OR H": [1, 'B4'],
    "OR L": [1, 'B5'],
    "OR N": [2, 'F6xx'],
    "OTDR": [1, 'EDBB'],
    "OTIR": [1, 'EDB3'],
    "OUT (C), A": [2, 'ED79'],
    "OUT (C), B": [2, 'ED41'],
    "OUT (C), C": [2, 'ED49'],
    "OUT (C), D": [2, 'ED51'],
    "OUT (C), E": [2, 'ED59'],
    "OUT (C), H": [2, 'ED61'],
    "OUT (C), L": [2, 'ED69'],
    "OUT (N), A": [2, 'D3xx'],
    "OUTD": [1, 'EDA3'],
    "OUTI": [1, 'EDAB'],
    "POP AF": [1, 'F1'],
    "POP BC": [1, 'C1'],
    "POP DE": [1, 'D1'],
    "POP HL": [1, 'E1'],
    "POP IX": [2, 'DDE1'],
    "POP IY": [2, 'FDE1'],
    "PUSH AF": [1, 'F5'],
    "PUSH BC": [1, 'C5'],
    "PUSH DE": [1, 'D5'],
    "PUSH HL": [1, 'E5'],
    "PUSH IX": [2, 'DDE5'],
    "PUSH IY": [2, 'FDE5'],
     "RES 0, (HL)": [2, 'CB86'],
    "RES 0, (IX + d)": [4, 'DDCBxx6E'],
    "RES 0, (IY + d)": [4, 'FDCBxx6E'],
    "RES 0, A": [2, 'CB87'],
    "RES 0, B": [2, 'CB80'],
    "RES 0, C": [2, 'CB81'],
    "RES 0, D": [2, 'CB82'],
    "RES 0, E": [2, 'CB83'],
    "RES 0, H": [2, 'CB84'],
    "RES 0, L": [2, 'CB85'],
    "RES 1, (HL)": [2, 'CB8E'],
    "RES 1, (IX + d)": [4, 'DDCBxx6E'],
    "RES 1, (IY + d)": [4, 'FDCBxx6E'],
    "RES 1, A": [2, 'CB8F'],
    "RES 1, B": [2, 'CB88'],
    "RES 1, C": [2, 'CB89'],
    "RES 1, D": [2, 'CB8A'],
    "RES 1, E": [2, 'CB8B'],
    "RES 1, H": [2, 'CB8C'],
    "RES 1, L": [2, 'CB8D'],
    "RES 2, (HL)": [2, 'CB96'],
    "RES 2, (IX + d)": [4, 'DDCBxx66'],
    "RES 2, (IY + d)": [4, 'FDCBxx66'],
    "RES 2, A": [2, 'CB97'],
    "RES 2, B": [2, 'CB90'],
    "RES 2, C": [2, 'CB91'],
    "RES 2, D": [2, 'CB92'],
    "RES 2, E": [2, 'CB93'],
    "RES 2, H": [2, 'CB94'],
    "RES 2, L": [2, 'CB95'],
    "RES 3, (HL)": [2, 'CB9E'],
    "RES 3, (IX + d)": [4, 'DDCBxx76'],
    "RES 3, (IY + d)": [4, 'FDCBxx76'],
    "RES 3, A": [2, 'CB9F'],
    "RES 3, B": [2, 'CB98'],
    "RES 3, C": [2, 'CB99'],
    "RES 3, D": [2, 'CB9A'],
    "RES 3, E": [2, 'CB9B'],
    "RES 3, H": [2, 'CB9C'],
    "RES 3, L": [2, 'CB9D'],
    "RES 4, (HL)": [2, 'CBA6'],
    "RES 4, (IX + d)": [4, 'DDCBxxA6'],
    "RES 4, (IY + d)": [4, 'FDCBxxA6'],
    "RES 4, A": [2, 'CBA7'],
    "RES 4, B": [2, 'CBA0'],
    "RES 4, C": [2, 'CBA1'],
    "RES 4, D": [2, 'CBA2'],
    "RES 4, E": [2, 'CBA3'],
    "RES 4, H": [2, 'CBA4'],
    "RES 4, L": [2, 'CBA5'],
    "RES 5, (HL)": [2, 'CBAE'],
    "RES 5, (IX + d)": [4, 'DDCBxxAE'],
    "RES 5, (IY + d)": [4, 'FDCBxxAE'],
    "RES 5, A": [2, 'CBAF'],
    "RES 5, B": [2, 'CBA8'],
    "RES 5, C": [2, 'CBA9'],
    "RES 5, D": [2, 'CBAA'],
    "RES 5, E": [2, 'CBAB'],
    "RES 5, H": [2, 'CBAC'],
    "RES 5, L": [2, 'CBAD'],
    "RES 6, (HL)": [2, 'CBB6'],
    "RES 6, (IX + d)": [4, 'DDCBxxB6'],
    "RES 6, (IY + d)": [4, 'FDCBxxB6'],
    "RES 6, A": [2, 'CBB7'],
    "RES 6, B": [2, 'CBB0'],
    "RES 6, C": [2, 'CBB1'],
    "RES 6, D": [2, 'CBB2'],
    "RES 6, E": [2, 'CBB3'],
    "RES 6, H": [2, 'CBB4'],
    "RES 6, L": [2, 'CBB5'],
    "RES 7, (HL)": [2, 'CBBE'],
    "RES 7, (IX + d)": [4, 'DDCBxxBE'],
    "RES 7, (IY + d)": [4, 'FDCBxxBE'],
    "RES 7, A": [2, 'CBBF'],
    "RES 7, B": [2, 'CBB8'],
    "RES 7, C": [2, 'CBB9'],
    "RES 7, D": [2, 'CBBA'],
    "RES 7, E": [2, 'CBBB'],
    "RES 7, H": [2, 'CBBC'],
    "RES 7, L": [2, 'CBBD'],
     "RET C": [1, 'D8'],
    "RET M": [1, 'F8'],
    "RET NC": [1, 'D0'],
    "RET NZ": [1, 'C0'],
    "RET P": [1, 'E8'],
    "RET PE": [1, 'E4'],
    "RET PO": [1, 'E0'],
    "RET Z": [1, 'C8'],
    "RETI": [1, 'ED4D'],
    "RETN": [1, 'ED45'],
    "RL (HL)": [2, 'CB16'],
    "RL (IX + d)": [4, 'DDCBxx16'],
    "RL (IY + d)": [4, 'FDCBxx16'],
    "RL A": [2, 'CB17'],
    "RL B": [2, 'CB10'],
    "RL C": [2, 'CB11'],
    "RL D": [2, 'CB12'],
    "RL E": [2, 'CB13'],
    "RL H": [2, 'CB14'],
    "RL L": [2, 'CB15'],
    "RLA": [1, '17'],
    "RLC (HL)": [2, 'CB06'],
    "RLC (IX + d)": [4, 'DDCBxx06'],
    "RLC (IY + d)": [4, 'FDCBxx06'],
    "RLC A": [2, 'CB07'],
    "RLC B": [2, 'CB00'],
    "RLC C": [2, 'CB01'],
    "RLC D": [2, 'CB02'],
    "RLC E": [2, 'CB03'],
    "RLC H": [2, 'CB04'],
    "RLC L": [2, 'CB05'],
    "RLCA": [1, '07'],
    "RLD": [1, 'ED6F'],
    "RR (HL)": [2, 'CB1E'],
    "RR (IX + d)": [4, 'DDCBxx1E'],
    "RR (IY + d)": [4, 'FDCBxx1E'],
    "RR A": [2, 'CB1F'],
    "RR B": [2, 'CB18'],
    "RR C": [2, 'CB19'],
    "RR D": [2, 'CB1A'],
    "RR E": [2, 'CB1B'],
    "RR H": [2, 'CB1C'],
    "RR L": [2, 'CB1D'],
    "RRA": [1, '1F'],
    "RRC (HL)": [2, 'CB0E'],
    "RRC (IX + d)": [4, 'DDCBxx0E'],
    "RRC (IY + d)": [4, 'FDCBxx0E'],
    "RRC A": [2, 'CB0F'],
    "RRC B": [2, 'CB08'],
    "RRC C": [2, 'CB09'],
    "RRC D": [2, 'CB0A'],
    "RRC E": [2, 'CB0B'],
    "RRC H": [2, 'CB0C'],
    "RRC L": [2, 'CB0D'],
    "RRCA": [1, '0F'],
    "RRD": [1, 'ED67'],
    "RST 0": [1, 'C7'],
    "RST 10H": [1, 'D7'],
    "RST 18H": [1, 'DF'],
    "RST 20H": [1, 'E7'],
    "RST 28H": [1, 'EF'],
    "RST 30H": [1, 'F7'],
    "RST 38H": [1, 'FF'],
    "RST 8": [1, 'CF'],
    "SBC A, (HL)": [1, '9E'],
    "SBC A, (IX + d)": [3, 'DD9Exx'],
    "SBC A, (IY + d)": [3, 'FD9Exx'],
    "SBC A, A": [1, '9F'],
    "SBC A, B": [1, '98'],
    "SBC A, C": [1, '99'],
    "SBC A, D": [1, '9A'],
    "SBC A, E": [1, '9B'],
    "SBC A, H": [1, '9C'],
    "SBC A, L": [1, '9D'],
    "SBC HL, BC": [1, 'DE20'],
    "SBC HL, DE": [1, 'ED42'],
    "SBC HL, HL": [1, 'ED52'],
    "SBC HL, SP": [1, 'ED62'],
    "SCF": [1, '37'],
    "SET 0, (HL)": [2, 'CB86'],
    "SET 0, (IX + d)": [4, 'DDCBxx6E'],
    "SET 0, (IY + d)": [4, 'FDCBxx6E'],
    "SET 0, A": [2, 'CB87'],
    "SET 0, B": [2, 'CB80'],
    "SET 0, C": [2, 'CB81'],
    "SET 0, D": [2, 'CB82'],
    "SET 0, E": [2, 'CB83'],
    "SET 0, H": [2, 'CB84'],
    "SET 0, L": [2, 'CB85'],
    "SET 1, (HL)": [2, 'CB8E'],
    "SET 1, (IX + d)": [4, 'DDCBxx6E'],
    "SET 1, (IY + d)": [4, 'FDCBxx6E'],
    "SET 1, A": [2, 'CB8F'],
    "SET 1, B": [2, 'CB88'],
    "SET 1, C": [2, 'CB89'],
    "SET 1, D": [2, 'CB8A'],
    "SET 1, E": [2, 'CB8B'],
    "SET 1, H": [2, 'CB8C'],
    "SET 1, L": [2, 'CB8D'],
    "SET 2, (HL)": [2, 'CB96'],
    "SET 2, (IX + d)": [4, 'DDCBxx66'],
    "SET 2, (IY + d)": [4, 'FDCBxx66'],
    "SET 2, A": [2, 'CB97'],
    "SET 2, B": [2, 'CB90'],
    "SET 2, C": [2, 'CB91'],
    "SET 2, D": [2, 'CB92'],
    "SET 2, E": [2, 'CB93'],
    "SET 2, H": [2, 'CB94'],
    "SET 2, L": [2, 'CB95'],
    "SET 3, (HL)": [2, 'CB9E'],
    "SET 3, (IX + d)": [4, 'DDCBxx76'],
    "SET 3, (IY + d)": [4, 'FDCBxx76'],
    "SET 3, A": [2, 'CB9F'],
    "SET 3, B": [2, 'CB98'],
    "SET 3, C": [2, 'CB99'],
    "SET 3, D": [2, 'CB9A'],
    "SET 3, E": [2, 'CB9B'],
    "SET 3, H": [2, 'CB9C'],
    "SET 3, L": [2, 'CB9D'],
    "SET 4, (HL)": [2, 'CBA6'],
    "SET 4, (IX + d)": [4, 'DDCBxxA6'],
    "SET 4, (IY + d)": [4, 'FDCBxxA6'],
    "SET 4, A": [2, 'CBA7'],
    "SET 4, B": [2, 'CBA0'],
    "SET 4, C": [2, 'CBA1'],
    "SET 4, D": [2, 'CBA2'],
    "SET 4, E": [2, 'CBA3'],
    "SET 4, H": [2, 'CBA4'],
    "SET 4, L": [2, 'CBA5'],
    "SET 5, (HL)": [2, 'CBAE'],
    "SET 5, (IX + d)": [4, 'DDCBxxAE'],
    "SET 5, (IY + d)": [4, 'FDCBxxAE'],
    "SET 5, A": [2, 'CBAF'],
    "SET 5, B": [2, 'CBA8'],
    "SET 5, C": [2, 'CBA9'],
    "SET 5, D": [2, 'CBAA'],
    "SET 5, E": [2, 'CBAB'],
    "SET 5, H": [2, 'CBAC'],
    "SET 5, L": [2, 'CBAD'],
    "SET 6, (HL)": [2, 'CBB6'],
    "SET 6, (IX + d)": [4, 'DDCBxxB6'],
    "SET 6, (IY + d)": [4, 'FDCBxxB6'],
    "SET 6, A": [2, 'CBB7'],
    "SET 6, B": [2, 'CBB0'],
    "SET 6, C": [2, 'CBB1'],
    "SET 6, D": [2, 'CBB2'],
    "SET 6, E": [2, 'CBB3'],
    "SET 6, H": [2, 'CBB4'],
    "SET 6, L": [2, 'CBB5'],
    "SET 7, (HL)": [2, 'CBBE'],
    "SET 7, (IX + d)": [4, 'DDCBxxBE'],
    "SET 7, (IY + d)": [4, 'FDCBxxBE'],
    "SET 7, A": [2, 'CBBF'],
    "SET 7, B": [2, 'CBB8'],
    "SET 7, C": [2, 'CBB9'],
    "SET 7, D": [2, 'CBBA'],
    "SET 7, E": [2, 'CBBB'],
    "SET 7, H": [2, 'CBBC'],
    "SET 7, L": [2, 'CBBD']


}